### ISSUE TITLE
Endless loop when using Logstash Logger together with Cm_RedisSession_Model_Session

### ISSUE THREAD

**Issue by cinzko** [firegento/firegento-logger#106]
When the Logstash-Logger is configured together with Cm_RedisSession_Model_Session an endless loop is produced.
This happens because of "\FireGento_Logger_Model_Logstash::buildJSONMessage":
 $fields['SessionId'] = Mage::getSingleton("core/session")->getEncryptedSessionId();
 $fields['CustomerId'] = Mage::getSingleton('customer/session')->getCustomerId();

The above calls cause the instantiation of "\Cm_RedisSession_Model_Session::__construct" which calls  "Mage::log(...)" which calls  "\FireGento_Logger_Model_Logstash::buildJSONMessage" and so on...

**Comment by cinzko** [comment]
a hotfix is to remove the 2 lines in  "\FireGento_Logger_Model_Logstash::buildJSONMessage":
$fields['SessionId'] = Mage::getSingleton("core/session")->getEncryptedSessionId();
$fields['CustomerId'] = Mage::getSingleton('customer/session')->getCustomerId();

**Comment by colinmollenhour** [comment]
The logger should not be instantiating new sessions.. Does something like this fix it?

```
if (isset($_SESSION)) {
    $fields['SessionId'] = Mage::getSingleton("core/session")->getEncryptedSessionId();
    $fields['CustomerId'] = Mage::getSingleton('customer/session')->getCustomerId();
}
```

**Comment by cinzko** [comment]
Yes, this works
Thanks a lot!
