### ISSUE TITLE
Why skip warn level ?

### ISSUE THREAD

**Issue by huynhphan89** [firegento/firegento-logger#109]
In Helper/Data, addPriorityFilter function, line 114
https://github.com/firegento/firegento-logger/blob/master/src/app/code/community/FireGento/Logger/Helper/Data.php#L114

Could you please explain why you skip warn level ?
Is there any reason ?
Thanks

**Comment by ToonSpinISAAC** [comment]
Unhelpful to link to a branch. You probably mean this: https://github.com/firegento/firegento-logger/blob/59f71547063a3ea63c1456c0206bd60bafbae2e0/src/app/code/community/FireGento/Logger/Helper/Data.php#L114

**Comment by ToonSpinISAAC** [comment]
In the version that's currently in master, the priority is no longer skipped. @huynhphan89, is there a reason this issue is still open?
