### ISSUE TITLE
Call to undefined function random_bytes()

### ISSUE THREAD

**Issue by SamKTaylor** [firegento/firegento-logger#127]
Fatal error: Call to undefined function random_bytes() in app/code/community/FireGento/Logger/Helper/Data.php on line 50

I cant see any information about what PHP version you are targeting but random_bytes() was only introduced in PHP7, Magento isnt php 7 compatible without changes.

**Comment by colinmollenhour** [comment]
Thanks for the report. While I strongly advise just upgrading to PHP 7 (is anyone still supporting 5.x?), if you want to add a `version_compare` and an alternative to fix support for older versions I think we would happily accept a PR.

**Comment by sam-vortex** [comment]
You could at least list PHP 7 as your targeted version in your readme

**Comment by speedupmate** [comment]
paragonie/random_compat is a polyfill for this method.
