### ISSUE TITLE
Security Issue when logging %requestData% 

### ISSUE THREAD

**Issue by SchumacherFM** [firegento/firegento-logger#24]
![screen shot 2014-03-14 at 2 37 57 pm](https://f.cloud.github.com/assets/372027/2417984/6987e412-ab32-11e3-85d0-ecc5eaa446f7.png)

Just discovered a security issue when I use the advanced logging format.

I'm logging failed payments in onepageController::saveOrderAction but %requestData% contains credit card details.

How can I strip of sensitiv request data from being logged without removing %requestData% from the advanced format? [Now I have removed it :-)]

The issue is here: https://github.com/firegento/firegento-logger/blob/develop/src/app/code/community/FireGento/Logger/Helper/Data.php#L257

It would be nice if there could be an event implemented with which you can modify the GET/POST/FILES/RAWPOST vars before being logged.

**Comment by airbone42** [comment]
Merged to dev
