### ISSUE TITLE
Sending exceptions to the configured services?

### ISSUE THREAD

**Issue by airbone42** [firegento/firegento-logger#42]
Thanks to all contributors of this extension. It's definitely a must-have for every Magento shop.

But is it also possible to send all exceptions to the configured external log services and not only all Mage::log calls?

**Comment by kojiromike** [comment]
It may not be feasible to send report exceptions. Such exceptions often happen when access to the database itself is broken, so it may be impossible for Firegento Logger to get its own configuration settings.

You could require that Firegento Logger be configured directly in app/etc/*.xml, but that would be a pretty significant change from this point.

**Comment by airbone42** [comment]
Even if we only catch the exceptions when the db is available this is no easy task. Unfortunately the exception handling seems pretty hardcoded in App.php which can not be rewritten, so also not changed in an elegant way.

Also registering an exception handle won't help as App.php catches the exception already and then just ends in a die(); :(

A not nice but probably way with the less problems would be to create a copy of Mage_Core_Exception in the local pool where we could implement the logging or at least a way to store the latest exception and then log it in a register shutdown function.

If anyone sees a better way please let me know.

We could alternatively scan the report directory via a cron and then send the reports async to the configured logging system. This won't work with dev mode on, only in production.

**Comment by airbone42** [comment]
Actually this is a duplicate of #34
