### ISSUE TITLE
I still have no idea what it actually logs

### ISSUE THREAD

**Issue by peterjaap** [firegento/firegento-logger#61]
Maybe include screenshots of output emails or New Relic overview or the configuration section in the README?

**Comment by datenbrille** [comment]
What kind of screenshots do you want? Configuration, output? New Relic is not implemented yet.

**Comment by peterjaap** [comment]
Yes and yes.

**Comment by razbakov** [comment]
I also don't understand the issue. @peterjaap can you describe the issue more specific, please?
