### ISSUE TITLE
Disable logging per module

### ISSUE THREAD

**Issue by mzeis** [firegento/firegento-logger#62]
Some extensions log useless stuff that pollutes the logs. In many cases the filter option won't suffice as these extensions don't prefix their log entries.

I'm not sure if it's easy to do that reliably, but @schmengler had a good idea: 

>  should be possible with defining a custom log writer in global/log/core/writer_model and some debug_backtrace magic. not the most elegant thing but at least doesn't require hacking Mage.php

**Comment by datenbrille** [comment]
Hi Matthias,

the suggested solution is the base of the FireGento-Logger:
```xml
<log>
            <core>
                <writer_model>FireGento_Logger_Model_Queue</writer_model>
```
But maybe I got something wrong?

**Comment by daim2k5** [comment]
Pease look at  PR #64

**Comment by mzeis** [comment]
Thanks for the reference to PR #64. I'll leave it open to you if you like the approach from #64 as I'm not involved with the FireGento-Logger-project. 

@datenbrille: I'm not sure if I do understand you correctly. :-) Yes, FireGento allows logging to different targets, but you cannot tell the logger at the moment that messages from extension Vendor_Abc should be logged but not from Vendor_Xyz, right? That's what my new feature request is about.

**Comment by datenbrille** [comment]
Ah understood. I will look into the PR, but this happens most of the time if a vender does not use log levels. With the correct level and filters this should be enough, or am I mistaken?

**Comment by mzeis** [comment]
Exactly.
