### ISSUE TITLE
Log session_id with all requests

### ISSUE THREAD

**Issue by paales** [firegento/firegento-logger#65]
This allows us to link multiple log entries together. We sometimes experience errors that might be caused by a previous encountered error, it would be nice if we could detect this.

**Comment by Zifius** [comment]
:+1: Maybe we should gather a team and create a todo list for DE/NL hackathons to improve things for this extension?

**Comment by datenbrille** [comment]
Every pull request is welcome. At the moment I have no time to develop the project any further. Sorry for that.

**Comment by Zifius** [comment]
No problem Karl, just looking for a list of must have or must resolve for this project. Not familiar yet with the code

**Comment by razbakov** [comment]
I added SessionId to Logstash in #78

**Comment by razbakov** [comment]
@Zifius what if we gather this weekend for a hackathon?

**Comment by colinmollenhour** [comment]
Both cookie and session data are supported in the current master so I think this has been effectively addressed.
