### ISSUE TITLE
How to log apache access and error log?

### ISSUE THREAD

**Issue by razbakov** [firegento/firegento-logger#79]
All our projects are hosted on shared hosting. We don't have access to install new packages.
I want to forward apache access and error log to remote logstash server.
Is there a way to do it? Does it make sense to write log forwarder with this extension?

**Comment by razbakov** [comment]
@Zifius @daim2k5 @datenbrille ?

**Comment by daim2k5** [comment]
Normally the syslog daemon is your friend ;-)

**Comment by razbakov** [comment]
Any hint?

**Comment by Flyingmana** [comment]
there is probably another endpoint needed then which can send to https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html
or https://www.elastic.co/guide/en/logstash/current/plugins-inputs-udp.html

**Comment by datenbrille** [comment]
So you would like to use magento as proxy to logstash? Possible but in most case you call the roster or install the packages to use syslog or other kind of forwarders. But to answer the question, it is possible. I would do that with a cron task.
