### ISSUE TITLE
Priority filter not working for defining which target to log to

### ISSUE THREAD

**Issue by pixelhed** [firegento/firegento-logger#86]
Priority Level Filter does not work when using multiple targets: 

For example when the mail target is set to `Zend_log::ALERT `and the Files (Magento Default) Configuration Target is set to` Zend_log::DEBUG` it is expected that ONLY alerts are sent to the email target, this is not the case.

The reason is that `Zend_Log_Filter_Priority::accept()` expects an array to be passed as a parameter but instead an object of type `FireGento_Logger_Model_Event` is passed, therefore the check:

`return version_compare($event['priority'], $this->_priority, $this->_operator);` 

fails and the `Zend_log::DEBUG` messages are sent to the Mail target as well.

**Comment by daim2k5** [comment]
Sorry i merged all the open PR.
